#!/bin/bash

expected_count=$(grep -o -w "internal-port" /etc/sysconfig/ivs | wc -w)
if [ $expected_count == 0 ]; then
    echo "No internal port is configured for ivs"
    exit 0
fi

MAX_RETRY=10

for ((count = 0; count < $MAX_RETRY; count++ )); do
    actual_count=$(ivs-ctl show | awk '/ivs:/,0{if (!/ivs:/)print}' | grep "(internal)" | grep -v "inband" | grep -v "ivs" | awk '{print $2}' | wc -l)
    if [ $actual_count -ge $expected_count ]; then
        break
    fi

    echo "wait for ivs to bring up internal ports"
    sleep 1
done

if [ $count -eq $MAX_RETRY ]; then
    echo "ivs internal ports are not created even after $MAX_RETRY seconds"
    exit -1
fi

intfs=$(ivs-ctl show | awk '/ivs:/,0{if (!/ivs:/)print}' | grep "(internal)" | grep -v "inband" | grep -v "ivs" | awk '{print $2}')
for intf in $intfs; do
    ifup $intf;
    echo "ifup ivs port $intf"
done
