#!/bin/bash

# Copyright (c) 2011 Alexey I. Froloff.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. /etc/init.d/functions

cd /etc/sysconfig/network-scripts
. ./network-functions

[ -f ../network ] && . ../network

CONFIG=${1}

need_config ${CONFIG}

source_config

case "$TYPE" in
        IVSIntPort)
                intf=$(ivs-ctl list-ports | grep "$DEVICE")
                if [ -z $intf ]; then
                    ivs-ctl add-internal-port "$DEVICE"
                fi
                if ! [ -z $IPADDR ]; then
                   ifconfig "$DEVICE" "$IPADDR" netmask "$NETMASK";
                elif ! [ -z $IPV6ADDR ]; then
                   ifconfig "$DEVICE" inet6 add "$IPV6ADDR";
                else
                   echo ERROR: Missing IP address for "$DEVICE" interface
                fi
                ;;
        *)
                /sbin/ip link set dev ${DEVICE} up
                intf=$(ivs-ctl list-ports | grep "$DEVICE")
                if [ -z $intf ]; then
                    ivs-ctl add-port "$DEVICE"
                fi
                ;;
esac

# Call ifup-post to setup routes for the interface
exec /etc/sysconfig/network-scripts/ifup-post "$CONFIG" "$2"
